source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def bugly
    pod 'Bugly'
end

target 'Tang' do
    
pod 'AFNetworking'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'FCUUID','1.3.1'
pod 'IQKeyboardManager', '~> 4.0.10'
pod 'JZNavigationExtension', '1.5.0.1'
pod 'MJRefresh'
pod 'ReactiveObjC', '~> 3.0'
pod 'SDWebImage', '~> 4.1.0'
pod 'SDWebImage/GIF', '~> 4.1.0'
pod 'SDWebImage/WebP', '~> 4.1.0'
pod 'SVProgressHUD'
pod 'WebViewJavascriptBridge', '~> 6.0.2'
pod 'YYCache'
pod 'YYCategories'
pod 'YYModel'
pod 'TMTumblrSDK' #https://github.com/tumblr/TMTumblrSDK
pod 'KTVHTTPCache', :git => 'https://github.com/ChangbaDevs/KTVHTTPCache.git'

bugly

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = 'Swift 4.0'
            config.build_settings['VALID_ARCHS'] = 'armv7 arm64'
            
            if config.build_settings['PRODUCT_NAME'] == 'CocoaHTTPServer'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DD_LEGACY_MACROS=1']
            end
        end
    end
end
