source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!
inhibit_all_warnings!

target ‘Tang’ do
    
pod 'AFNetworking'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'FCUUID','1.3.1'
pod 'IQKeyboardManager', '~> 4.0.10'
pod 'JZNavigationExtension'
pod 'MJRefresh'
pod 'ReactiveObjC', '~> 3.0'
pod 'SDWebImage', '~> 4.1.0'
pod 'SVProgressHUD'
pod 'WebViewJavascriptBridge', '~> 6.0.2'
pod 'YYCache'
pod 'YYCategories'
pod 'YYModel'

end

